version: "3.8"

services:
  notebook:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fleet_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
    working_dir: /app

  fleet_job:
    build:
      context: .
      dockerfile: docker/Dockerfile.job
    container_name: fleet_job
    volumes:
      - ./data:/app/data
    environment:
      - DATA_PATH=/app/data

  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow
    depends_on:
      - fleet_job
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - DATA_HOST_PATH=/home/vyshaksv/git-projects/fleet-optimization-batch/data
    volumes:
      - ./airflow_home:/opt/airflow
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    ports:
      - "8080:8080"
    user: "${UID}:${GID}"
    command:  bash -c "
      airflow scheduler & airflow webserver
      "